### ISSUE TITLE
Installatiom

### ISSUE THREAD

**Issue by voodookult** [xCENTx/Borderlands-GOTY-Enhanced-Trainer-Source#1]
Hi. I've been trying to download the trainer but I can't find the .exe file so I can't use it. Where can I get it to make it work? I can't find any other trainer with XP multiplier like this one

**Comment by xCENTx** [comment]
> Hi. I've been trying to download the trainer but I can't find the .exe file so I can't use it. Where can I get it to make it work? I can't find any other trainer with XP multiplier like this one

You can either build it from source or go to UnknownCheats where i have posted the compiled binary
[FORUM POST](https://www.unknowncheats.me/forum/other-fps-games/456151-borderlands-goty-enhanced-simple-trainer.html)

**Comment by voodookult** [comment]
Sorry to waste your time, but I have no idea what "build" means I have no knowledge of any basic code or computers and I am not English native I don't think I understand what do I have to do. Besides, I tried UC but it says the link is pending approval, so I can't download it from there either.

**Comment by xCENTx** [comment]
You'll have to wait for it to be approved. Due to how the forum operates I cannot post the compiled source here. That whole post is revolved around this repository. You will either have to download visual studio 2019 to build the project or wait patiently. Sorry
